version: '3.1'

# volumes:
#   npm_node_modules:
#   composer_vendor:

services:
  # app:
  #   tty: true
  #   image: docker.io/bitnami/laravel:7-debian-10
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 3306
  #     DB_DATABASE: $DB_DATABASE
  #     DB_USERNAME: $DB_USERNAME
  #     DB_PASSWORD: $DB_PASSWORD
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - npm_node_modules:/app/node_modules
  #     - composer_vendor:/app/vendor
  #     - ./:/app
  db:
    image: mariadb
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
    ports:
      - 8082:80
